config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness.urls')),
    path('accounts/', include('allauth.urls')),
]

fitness/urls.py
from django.urls import path
from . import views

app_name    = 'fitness'
urlpatterns = [
    path('', views.Home, name="home"),
    path('fitness_category/', views.fitness_category, name="fitness_category"),
    path('menu/', views.menu, name="menu"),
    path('menu/<uuid:pk>/', views.menu, name="menu_single"),

]

fitness/models.py
from django.db import models

from django.core.validators import MinValueValidator,MaxValueValidator
from django.utils import timezone
from django.db.models import Sum

from django.conf import settings

import uuid


#DurationFieldの表示用処理
def duration_format(total,input_format=False):

    hours   = str( total // 3600 )
    minutes = str( (total % 3600) // 60)
    seconds = str( (total % 60) )

    if input_format:
        return '{}:{}:{}'.format(hours.zfill(2), minutes.zfill(2), seconds.zfill(2))
    else:
        return '{}時間{}分{}秒'.format(hours, minutes, seconds)



class FitnessCategory(models.Model):
    id      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt      = models.DateTimeField(verbose_name="登録日時",default=timezone.now)
    name    = models.CharField(verbose_name="フィットネスカテゴリ名",max_length=20)
    kcal    = models.IntegerField(verbose_name="1分あたりの消費カロリー",validators=[MinValueValidator(0)])

    """
    #合計のtimedelta型
    def time_total(self):
        memories    = FitnessMemory.objects.filter(category=self.id).aggregate(Sum("time"))
        return memories["time__sum"]

    #合計の時間
    def time_total_format(self):
        td   = self.time_total()

        if td:
            return duration_format(int(td.total_seconds()))
        else:
            return duration_format(0)
    """

    user        = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="投稿者",on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class FitnessMemory(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt          = models.DateTimeField(verbose_name='登録日時', default=timezone.now)

    exe_dt      = models.DateTimeField(verbose_name='実施日時')

    category    = models.ForeignKey(FitnessCategory, verbose_name='カテゴリー', on_delete=models.SET_NULL, null=True)
    time        = models.DurationField(verbose_name="運動時間")
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="投稿者",on_delete=models.CASCADE)



    def time_format(self):
        return duration_format( int(self.time.total_seconds()) )

    def __str__(self):
        return self.id


#間食、朝食などで仕分けることで後に検索に利用する←グラフ化
class FoodCategory(models.Model):
    id      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt      = models.DateTimeField(verbose_name='登録日時', default=timezone.now)

    name    = models.CharField(verbose_name="食事の種類",max_length=15)


class FoodMemory(models.Model):
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt          = models.DateTimeField(verbose_name='登録日時', default=timezone.now)
    img         = models.ImageField(verbose_name='食事画像', upload_to='fitness/food/')
    kcal        = models.IntegerField(verbose_name='摂取したカロリー', validators=[MinValueValidator(0)])

    exe_dt      = models.DateTimeField(verbose_name='実施日時')

    category    = models.ForeignKey(FoodCategory,verbose_name="カテゴリ",on_delete=models.CASCADE,null=True,blank=True)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="投稿者",on_delete=models.CASCADE)

    def __str__(self):
        return self.id

class Menu(models.Model):
    id      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt      = models.DateTimeField(verbose_name='登録日時', default=timezone.now)
    name    = models.CharField(verbose_name='名前', max_length=20)
    user    = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="投稿者",on_delete=models.CASCADE)


    def details(self):
        return MenuDetail.objects.filter(menu=self.id).order_by("sort")

    def __str__(self):
        return self.name

class MenuDetail(models.Model):
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt          = models.DateTimeField(verbose_name='登録日時', default=timezone.now)

    menu        = models.ForeignKey(Menu, verbose_name='メニュー', on_delete=models.SET_NULL, null=True)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="投稿者",on_delete=models.CASCADE)

    time        = models.DurationField(verbose_name="運動時間")
    category    = models.ForeignKey(FitnessCategory, verbose_name='カテゴリー', on_delete=models.SET_NULL, null=True)

    sort        = models.IntegerField(verbose_name="順番")

    def time_format(self):
        return duration_format( int(self.time.total_seconds()) )

    #DurationFieldのtimeを00:00:00のフォーマットで返却するメソッド
    def time_input_format(self):
        return duration_format( int(self.time.total_seconds()), input_format=True )

    def __str__(self):
        return self.id

class Trophy(models.Model):
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dt          = models.DateTimeField(verbose_name='登録日時', default=timezone.now)
    name        = models.CharField(verbose_name='名前', max_length=20)
    img         = models.ImageField(verbose_name='トロフィー画像', upload_to='fitness/trophy/')

    #TODO:ユーザーモデルの多対多のフィールド
    user        = models.ManyToManyField(settings.AUTH_USER_MODEL,through='TrophyUser')

    def __str__(self):
        return self.name

#TODO:トロフィーモデルとユーザーモデルの中間テーブルに値するモデルを作る(明示的に作る)
class TrophyUser(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    trophy      = models.ForeignKey(Trophy,on_delete=models.CASCADE)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="登録者",on_delete=models.CASCADE)
    dt          = models.DateTimeField(verbose_name='登録日時', default=timezone.now)

fitness/forms.py
from django import forms

from django.core.validators import MinValueValidator, MaxValueValidator

from .models import FitnessCategory,FitnessMemory,Menu,MenuDetail


# 年月検索用バリデーションフォーム
class YearMonthForm(forms.Form):
    year    = forms.IntegerField()
    month   = forms.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])


class FitnessCategoryForm(forms.ModelForm):
    class Meta:
        model   = FitnessCategory
        fields  = ["name","kcal","user",]

class FitnessMemoryForm(forms.ModelForm):

    class Meta:
        model   = FitnessMemory
        fields  = ["category","time","user","exe_dt"]


class MenuForm(forms.ModelForm):
    class Meta:
        model   = Menu
        fields  = ["name","user"]

class MenuDetailForm(forms.ModelForm):
    class Meta:
        model   = MenuDetail
        fields  = ["category","menu","time","user","sort"]


class UUIDForm(forms.Form):
    id  = forms.UUIDField()

fitness/views.py
from django.shortcuts import render,redirect

from rest_framework.views import APIView as View

from django.contrib.auth.mixins import LoginRequiredMixin

from django.http.response import JsonResponse
from django.template.loader import render_to_string

from . import calendar
from .models import FitnessCategory,FitnessMemory,FoodCategory,FoodMemory,Menu,MenuDetail,Trophy,TrophyUser
from .forms import YearMonthForm,FitnessCategoryForm,FitnessMemoryForm,MenuForm,MenuDetailForm,UUIDForm

import datetime


class HomeView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):

        context = {}

        #カレンダーの表示
        form    = YearMonthForm(request.GET)
        today   = datetime.date.today()

        if form.is_valid():
            cleaned         = form.clean()
            selected_date   = datetime.datetime(year=cleaned["year"], month=cleaned["month"], day=1)
        else:
            selected_date   = datetime.datetime(year=today.year, month=today.month, day=1)

        context["selected_date"]                        = selected_date

        #TODO:FitnessMemoryの概要を含める
        context["month_date"]                           = calendar.create_calendar(selected_date.year, selected_date.month)

        context["months"], context["years"]             = calendar.create_months_years(selected_date, today)
        context["last_month"], context["next_month"]    = calendar.create_last_next_month(selected_date)

        context["categories"]   = FitnessCategory.objects.filter(user=request.user.id).order_by("-dt")
        context["menus"]        = Menu.objects.filter(user=request.user.id).order_by("-dt")


        return render(request, 'fitness/home.html' ,context)

Home = HomeView.as_view()



class FitnessCategoryView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        pass

    def post(self, request, *args, **kwargs):

        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form            = FitnessCategoryForm(copied)

        if form.is_valid():
            form.save()

        return redirect("fitness:home")

    def put(self, request, *args, **kwargs):
        pass
    def delete(self, request, *args, **kwargs):
        pass

fitness_category = FitnessCategoryView.as_view()

class FitnessMemoryView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):
        pass

    def post(self, request, *args, **kwargs):

        #TODO:以下3つのケースでFitnessMemoryを受け付ける

        #1:ストップウォッチから運動したケース
        #2:フィットネスメニューから運動したケース
        #3:手動記録追加にて手動で追加したケース

        categories  = request.POST.getlist("category")
        times       = request.POST.getlist("time")
        exe_dts     = request.POST.getlist("exe_dt")

        for category,time,exe_dt in zip(categories, times, exe_dts):
            dic = {}

            dic["category"] = category
            dic["time"]     = time
            dic["exe_dt"]   = exe_dt
            dic["user"]     = request.user.id

            form    = FitnessMemoryForm(dic)

            if form.is_valid():
                form.save()


        #TODO:レンダリングは左の領域を返す。

        pass


    def put(self, request, *args, **kwargs):
        pass
    def delete(self, request, *args, **kwargs):
        pass

fitness_memory = FitnessMemoryView.as_view()



class FoodCategoryView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        pass
    def post(self, request, *args, **kwargs):
        pass
    def put(self, request, *args, **kwargs):
        pass
    def delete(self, request, *args, **kwargs):
        pass

food_category   = FoodCategoryView.as_view()



class FoodMemoryView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        pass
    def post(self, request, *args, **kwargs):
        pass
    def put(self, request, *args, **kwargs):
        pass
    def delete(self, request, *args, **kwargs):
        pass


class MenuView(LoginRequiredMixin,View):

    def render_menu(self, request, context):
        context["categories"]   = FitnessCategory.objects.filter(user=request.user.id).order_by("-dt")
        context["menus"]        = Menu.objects.filter(user=request.user.id).order_by("-dt")

        return render_to_string("fitness/fitness_menu.html", context, request)

    def get(self, request, *args, **kwargs):
        pass

    def post(self, request, *args, **kwargs):
        data        = {"error":True}

        #ここからMenuとMenuDetailを連続で保存する。

        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form    = MenuForm(copied)

        if not form.is_valid():
            print(form.errors)
            return JsonResponse(data)
            #return redirect("fitness:home")

        #Menuの保存(返り値はMenuDetailのmenuフィールドで使うので取っておく)
        menu    = form.save()

        #MenuDetailの保存処理(同じname属性が複数ある場合、全て取得するには、.getlist()を使う。返り値はリスト)
        times       = request.POST.getlist("time")
        categories  = request.POST.getlist("category")

        sort        = 1

        #zipを使って2つのリストを同時にループする。
        for time,category in zip(times, categories):

            dic             = {}
            dic["user"]     = request.user.id
            dic["menu"]     = menu.id
            dic["time"]     = time
            dic["category"] = category
            dic["sort"]     = sort

            form            = MenuDetailForm(dic)

            if form.is_valid():
                print("保存")
                form.save()
            else:
                print(form.errors)

            sort += 1

        context = {}

        data["content"]     = self.render_menu(request,context)
        data["error"]       = False

        return JsonResponse(data)

    #この編集はMenuとMenuDetailの編集を兼ねる
    def put(self, request, *args, **kwargs):
        data        = {"error":True}

        #編集対象のMenuが指定されていない場合は終わる
        if "pk" not in kwargs:
            return JsonResponse(data)

        #Menuの編集
        menu        = Menu.objects.filter(id=kwargs["pk"],user=request.user.id).first()

        if not menu:
            return JsonResponse(data)

        copied          = request.data.copy()
        copied["user"]  = request.user.id

        form    = MenuForm(copied, instance=menu)

        if not form.is_valid():
            print(form.errors)
            return JsonResponse(data)

        menu    = form.save()

        #MenuDetailの編集

        #MenuDetailのidを抜き取る
        id_list     = request.POST.getlist("id")
        times       = request.POST.getlist("time")
        categories  = request.POST.getlist("category")

        sort        = 1
        for id,time,category in zip(id_list, times, categories):

            #編集対象のMenuDetailの特定
            #ここで空欄の場合は検索しないようにしておかないと、有効なUUIDではありませんというエラーができて、MenuDetailの追加ができない。
            #ここはuuid型であることをチェックしたほうがよい(現状空文字列とUUIDの2種類しか入らないので、これでも機能はする)
            if id:
                menu_detail = MenuDetail.objects.filter(id=id,user=request.user.id).first()
            else:
                menu_detail = None

            dic             = {}
            dic["user"]     = request.user.id
            dic["menu"]     = menu.id
            dic["time"]     = time
            dic["category"] = category
            dic["sort"]     = sort

            #ここでmenu_detailがNoneなら新しく追加される
            form            = MenuDetailForm(dic, instance=menu_detail)

            if form.is_valid():
                form.save()
            else:
                print(form.errors)

            sort += 1

        context = {}
        data["content"]     = self.render_menu(request,context)
        data["error"]       = False

        return JsonResponse(data)
        
    #ここの削除はMenuとMenuDetailの削除を兼ねる
    def delete(self, request, *args, **kwargs):
        data        = {"error":True}
        context     = {}

        if "pk" not in kwargs:
            return JsonResponse(data)

        #Menuの削除
        menu        = Menu.objects.filter(id=kwargs["pk"],user=request.user.id).first()

        if menu:
            menu.delete()
            data["content"] = self.render_menu(request,context)
            data["error"]   = False
            return JsonResponse(data)

        #MenuDetailの削除
        menu_detail = MenuDetail.objects.filter(id=kwargs["pk"],user=request.user.id).first()

        if menu_detail:
            menu_detail.delete()
            data["content"] = self.render_menu(request,context)
            data["error"]   = False

        return JsonResponse(data)

menu    = MenuView.as_view()

"""
class TrophyView(LoginRequiredMixin,View):
class TrophyUserView(LoginRequiredMixin,View):
"""

templates/fitness/fitness_menu.html
{% for menu in menus %}
<div class="menu_content_area">
    <input id="{{ menu.id }}" class="menu_edit_chk" type="checkbox">

    {# 平時に表示する領域 #}
    <div class="menu_content">
        <h3>{{ menu.name }}</h3>
        {# これがMenuの削除ボタン #}

        <form action="{% url 'fitness:menu_single' menu.id %}" style="display:inline-block;">
            <input class="menu_delete" type="button" value="削除">
        </form>
        <label class="menu_edit_label" for="{{ menu.id }}">編集</label>

        {# このメニューを始める時はこのボタンを押し、JavaScriptを発動させる。(カテゴリと時間をタイマーにセット) #}
        <form style="display:inline-block;">
            {% for detail in menu.details %}
            <input type="hidden" name="category" value="{{ detail.category.id }}">
            <input type="hidden" name="category_name" value="{{ detail.category.name }}">
            <input type="hidden" name="time" value="{{ detail.time.total_seconds }}">
            {% endfor %}
            <input class="menu_start" type="button" value="このメニューを始める">
        </form>


        {% for detail in menu.details %}
        <div class="row">
            <div class="col">{{ detail.category }} : {{ detail.time_format }}</div>
            <div class="col">
                <form action="{% url 'fitness:menu_single' detail.id %}">
                    <input class="menu_delete" type="button" value="削除">
                </form>
            </div>
        </div>
        {% endfor %}




    </div>

    {# 編集時に表示する領域 #}
    <div class="menu_edit">
        <label class="menu_edit_label" for="{{ menu.id }}">編集キャンセル</label>

        <form action="{% url 'fitness:menu_single' menu.id %}">
        
            <input type="text" name="name" value="{{ menu.name }}">
            <input class="menu_detail_create_row_add" type="button" value="追加">


            <div class="menu_detail_create_form">

                {% for detail in menu.details %}
                <div class="menu_detail_create_row">
                    <i class="fas fa-bars handle"></i>
                    <select name="category">
                        <option value="">フィットネスカテゴリを選んでください</option>
                        {% for category in categories %}
                        <option value="{{ category.id }}" {% if detail.category.id == category.id %}selected{% endif %}>{{ category.name }}</option>
                        {% endfor %}
                    </select>
                    <input type="text" name="time" placeholder="00:00:00" value="{{ detail.time_input_format }}">
                    <input type="hidden" name="id" value="{{ detail.id }}">
                </div>
                {% endfor %}

                {# ここに追加される #}

            </div>

            <input class="menu_edit_submit" type="button" value="送信">
        </form>

    </div>
</div>
{% endfor %}

templates/fitness/home.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>フィットネス</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    {# flatpickr #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>




    {# TODO:sortablejsで並び替えを実現する #}
    {# 今回の並び替えの処理はgetlistで上から順にとっていくだけなので、inputタグを用意してsortの値を入れる必要はない。 #}
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

    <link rel="stylesheet" href="{% static 'fitness/css/home.css' %}">

    <script src="{% static 'common/js/ajax.js' %}"></script>

    <script src="{% static 'fitness/js/home.js' %}"></script>
    <script src="{% static 'fitness/js/watch_and_timer.js' %}"></script>

</head>
<body>

    <div class="row mx-0">

        <div class="col-sm-6">
            {# カレンダー #}
            <div class="calender_header">
                <div class="calender_link_area">
                    <a href="?year={{ last_month.year }}&month={{ last_month.month }}"><i class="fas fa-angle-left"></i></a>
                </div>

                <form class="calender_form_area" action="" method="GET">
                    <select name="year">
                        {% for year in years %}
                        <option value="{{ year }}"  {% if year == selected_date.year %}selected{% endif %}>{{ year }}年</option>
                        {% endfor %}
                    </select>
                    <select name="month">
                        {% for month in months %}
                        <option value="{{ month }}" {% if month == selected_date.month %}selected{% endif %}>{{ month }}月</option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="検索">
                </form>

                <div class="calender_link_area">
                    <a href="?year={{ next_month.year }}&month={{ next_month.month }}"><i class="fas fa-angle-right"></i></a>
                </div>
            </div>

            <table class="calender">
                <thead>
                    <tr class="calender_head">
                        <td>日</td>
                        <td>月</td>
                        <td>火</td>
                        <td>水</td>
                        <td>木</td>
                        <td>金</td>
                        <td>土</td>
                    </tr>
                </thead>
                <tbody>
                    {% for week_date in month_date %}
                    <tr>
                        {% for date in week_date %}
                        <td>{{ date.day }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-6">


            <div class="container_area">
                <h2>カテゴリ追加</h2>

                <form action="{% url 'fitness:fitness_category' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="name" placeholder="カテゴリ名">
                    <input type="number" name="kcal" placeholder="1分あたりの消費カロリー">
                    <input type="submit" value="送信">
                </form>
            </div>

            <div class="container_area">
                <h2>手動記録追加</h2>

                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="text" name="exe_dt">
                    <select name="category">
                        <option value="">カテゴリを選んでください</option>
                        {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                    <input type="text" name="time" placeholder="00:00:00">
                    <input type="submit" value="送信">
                </form>
            </div>



            {# TODO:この部分は、フィットネスメニューを実行する時に表示させる #}
            {# TODO:タイマーが切れた時、音声で通知する #}
            {% comment %}
            <h2>タイマー</h2>

            <label><input id="timer_hour"   type="number" min="0" max="99" value="0">時間</label>
            <label><input id="timer_minute" type="number" min="0" max="59" value="0">分</label>
            <label><input id="timer_second" type="number" min="0" max="59" value="0">秒</label>
            <div>
                <input id="timer_start" type="button" value="スタート/一時停止">
                <input id="timer_reset"  type="button" value="リセット" style="display:none;">
            </div>
            <div id="remain">00時間00分00秒</div>
            {% endcomment %}


            {# TODO:この部分は、フィットネスカテゴリを選んだ上で運動を始める #}
            <div class="container_area">
                <h2>ストップウォッチ</h2>

                <select name="category">
                    <option value="">フィットネスカテゴリを選んでください</option>
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>

                {# ここの部分は:で区切るべきではなかろうか？Ajaxで送信する時、正規表現が必要になり、やや複雑になると思われる。 #}
                <div id="progress"></div>

                <input id="watch_start" type="button" value="スタート/一時停止">
                <input id="watch_rap"   type="button" value="ラップ" style="display:none;">
                <input id="watch_reset" type="button" value="リセット" style="display:none;">

                <div id="rap_area"></div>
            </div>


            <div class="container_area">

                {# TODO:フィットネスメニュー新規作成 #}
                <h2>フィットネスメニュー新規作成</h2>

                {# ↓MenuDetailのフォームの原型。これをJSで#menu_detail_create_formに追加する #}
                <div id="menu_detail_create_init" class="menu_detail_create_init">

                    <div class="menu_detail_create_row">
                        <i class="fas fa-bars handle"></i>
                        <select name="category">
                            <option value="">フィットネスカテゴリを選んでください</option>
                            {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                        <input type="text" name="time" placeholder="00:00:00">
                        <input class="menu_detail_create_delete" type="button" value="削除">
                        <input type="hidden" name="id" value="">
                    </div>
                </div>
                <form action="{% url 'fitness:menu' %}" method="POST">
                    {% csrf_token %}
                    {# ↓Menuのフォーム #}
                    <input type="text" name="name" placeholder="メニュー名">

                    {# TODO:追加ボタンは編集時にも使うので、class名に変更 #}
                    <input class="menu_detail_create_row_add" type="button" value="追加">
                    <div class="menu_detail_create_form">
                        {# ここにDetailフォームが追加される。 #}
                    </div>

                    <input id="menu_create_submit" type="button" value="送信">
                </form>
            </div>

            <div class="container_area">
                {# TODO:ここにフィットネスメニュー一覧を表示、削除と編集を受け付ける。 #}
                <h2>フィットネスメニュー一覧</h2>
                <div id="fitness_menu_area">
                    {% include "fitness/fitness_menu.html" %}
                </div>
            </div>

        </div>
    </div>

</body>
</html>